CliMA/ClimaCalibrate.jl

Project.toml
This deals with CompatHelper in one PR
=> Add proper compat

experiments/pipeline.sh, experiments/sphere_held_suarez_rhoe_equilmoist/generate_observations.sbatch
=> Move the pipeline to the new partition

experiments/sphere_held_suarez_rhoe_equilmoist/Manifest.toml, experiments/sphere_held_suarez_rhoe_equilmoist/Project.toml, experiments/sphere_held_suarez_rhoe_equilmoist/generate_observations.sbatch, experiments/sphere_held_suarez_rhoe_equilmoist/observation_map.jl, pipeline.sh, slurm/update.sbatch
=> Use ClimaAnalysis for sphere HS observation map

src/ekp_interface.jl
=> Inline model_config in @threaded

docs/src/experiment_setup_guide.md, experiments/sphere_held_suarez_rhoe_equilmoist/generate_observations.sbatch, experiments/sphere_held_suarez_rhoe_equilmoist/observation_map.jl, experiments/surface_fluxes_perfect_model/Manifest.toml, experiments/surface_fluxes_perfect_model/generate_truth.jl, experiments/surface_fluxes_perfect_model/observation_map.jl, pipeline.sh, slurm/initialize.sbatch, slurm/model_run.sbatch, slurm/parse_commandline.sh, slurm/update.sbatch, src/ekp_interface.jl
Content
- Add convenience functions for saving observation map output and getting EKP config
- Add an option for generating perfect model data in the CLI
- Rename output logs
- Clean up some julia code in the sbatch files
=> Clean up slurm pipeline

Project.toml, experiments/surface_fluxes_perfect_model/Manifest.toml, experiments/surface_fluxes_perfect_model/model_interface.jl, ext/CESExt.jl, src/emulate_sample.jl, test/Project.toml
=> Add extension for CES

.buildkite/pipeline.yml, Project.toml, README.md, docs/Project.toml, docs/make.jl, docs/src/api.md, docs/src/emulate_sample.md, docs/src/index.md, docs/src/precompilation.md, docs/src/quickstart.md, experiments/surface_fluxes_perfect_model/Manifest.toml, experiments/surface_fluxes_perfect_model/Project.toml, experiments/surface_fluxes_perfect_model/generate_data.jl, experiments/surface_fluxes_perfect_model/model_interface.jl, experiments/surface_fluxes_perfect_model/observation_map.jl, experiments/surface_fluxes_perfect_model/postprocessing.jl, ext/CESExt.jl, src/ClimaCalibrate.jl, src/backends.jl, test/Project.toml, test/caltech_hpc_e2e.jl, test/ekp_interface.jl, test/emulate_sample.jl, test/model_interface.jl, test/pure_julia_e2e.jl, test/slurm_unit_tests.jl
=> Rename CalibrateAtmos -> ClimaCalibrate

experiments/surface_fluxes_perfect_model/Manifest.toml, src/ClimaCalibrate.jl, src/backends.jl, src/ekp_interface.jl, src/slurm.jl, test/Project.toml, test/caltech_hpc_e2e.jl, test/slurm_unit_tests.jl
=> Use dict of slurm args instead of individual args

src/backends.jl, src/ekp_interface.jl, src/model_interface.jl, src/slurm.jl, test/ekp_interface.jl, test/model_interface.jl, test/pure_julia_e2e.jl, test/slurm_unit_tests.jl
=> Separate out ExperimentConfig, update docstrings

.buildkite/clima_server_test/pipeline.yml, src/backends.jl, src/ekp_interface.jl, src/slurm.jl, test/slurm_backend_e2e.jl, test/slurm_unit_tests.jl
=> Add Clima GPU server test

Project.toml
=> Release version 0.0.1

docs/src/api.md, src/backends.jl, src/ekp_interface.jl, src/model_interface.jl, src/slurm.jl
=> Export useful things

.buildkite/clima_server_test/pipeline.yml, .buildkite/pipeline.yml, Project.toml, README.md, docs/make.jl, docs/src/api.md, docs/src/index.md, src/ClimaCalibrate.jl, src/backends.jl, src/ekp_interface.jl, src/pbs.jl, src/slurm.jl, test/ekp_interface.jl, test/hpc_backend_e2e.jl, test/pbs_unit_tests.jl, test/slurm_unit_tests.jl
This PR adds a controller for PBS Pro and a backend for [NCAR Derecho](https://ncar-hpc-docs.readthedocs.io/en/latest/compute-systems/derecho/).
=> Add PBS controller, DerechoBackend

.buildkite/clima_server_test/pipeline.yml, .buildkite/pipeline.yml, Project.toml, src/backends.jl, test/Project.toml
=> Add pmap for backend

src/ekp_interface.jl, test/ekp_interface.jl
=> Enable EKP struct as input arg for initialize

docs/src/backends.md, docs/src/index.md, docs/src/quickstart.md
=> Update documentation 

Project.toml, src/workers.jl
=> Fix srun argument passing for SlurmManager

src/backends.jl
Pass ekp kwargs to ekp_constructor in `calibrate()`
=> Pass ekp kwargs

.buildkite/clima_server_test/pipeline.yml, .buildkite/derecho_pipeline.yml, .buildkite/pipeline.yml, .github/workflows/ci.yml, src/backends.jl, src/ekp_interface.jl, src/workers.jl, test/hpc_backend.jl, test/worker_backend.jl
=> Add restarts for all AbstractBackends

Project.toml, src/workers.jl
=> Fix duplicate worker status messages in PBS job polling

experiments/surface_fluxes_perfect_model/Manifest.toml, experiments/surface_fluxes_perfect_model/utils.jl, src/backends.jl, test/hpc_backend.jl, test/worker_backend.jl
=> Retrieve ensemble_size from EKP object instead of passing as parameter

docs/src/api.md, src/backends.jl, src/ekp_interface.jl
=> Simplify ensemble update with helper function

src/ekp_interface.jl
=> Improve checks for last completed iteration

Project.toml, test/pbs_unit_tests.jl
This PR widens the compat with CalibrateEmulateSample, allowing for full compatibility with all EnsembleKalmanProcesses versions.
----
=> Fix compat for CES.jl

Project.toml, docs/literate_example.jl, experiments/surface_fluxes_perfect_model/Manifest.toml, src/backends.jl, src/workers.jl
Closes #164 
Fixes the failure_rate kwarg when using the WorkerBackend and improved the error message to be more informative
----
=> Fix failure_rate kwarg in WorkerBackend, improve error message

docs/src/api.md, docs/src/quickstart.md, src/ekp_interface.jl, src/model_interface.jl, test/julia_backend.jl, test/model_interface.jl
closes #161 - This PR adds `post_observation_map_hook` and `postprocess_g_ensemble`.
=> Add post_observation_map_hook and postprocess_g_ensemble

.buildkite/clima_gpu_pipeline.yml, .buildkite/derecho_pipeline.yml, .buildkite/pipeline.yml, Project.toml, src/backends.jl
closes #171 - This PR adds Dates as a dependency and pretty format the iteration time.
=> Pretty format iteration time

Project.toml
This PR releases a new minor version, allowing us to make patch releases that are not considered breaking.
----
=> Release minor version

src/backends.jl, src/slurm.jl, test/slurm_unit_tests.jl
- Add documentation for the module load string 
- Add --threads for GPU runs
----
=> Add fixes for GCPBackend

src/ekp_interface.jl, src/workers.jl, test/pbs_manager_unit_tests.jl, test/slurm_manager_unit_tests.jl
Closes #178
Closes #176
Closes #146
----
=> Add try/catch for `analyze_iteration`, add `time` kwarg to `add_workers`, and save prior to disk

Project.toml, test/runtests.jl
=> Add CESExt tests back

.github/workflows/julia_formatter.yml, docs/Project.toml, docs/src/api.md, src/ekp_interface.jl, src/workers.jl, test/ekp_interface.jl
Closes #189 
- Add a helper function `load_latest_ekp`
- Downgrade JuliaFormatter to match other repo versions.
----
=> Add helper function to load EKP file

Project.toml, test/aqua.jl
This commit adds an entry for ClimaParams and Conda and updates the Aqua test for checking compat dependencies.
=> Add missing entries to compat

ext/ClimaAnalysisExt.jl, src/observation_recipe.jl, test/observation_recipe.jl
This commit adds latitude weighting to the seasonal diagonal covariance matrix.
=> Add latitude weighing

experiments/surface_fluxes_perfect_model/utils.jl, src/pbs.jl, test/pbs_unit_tests.jl
Fixes `DerechoBackend`. Closes #207 
Properly passes `exeflags` kwarg through to `pbs_model_run` to match the slurm implementation
----
=> Fix `DerechoBackend`

src/ekp_interface.jl
=> Fix stacktrace print for try/catch
