CliMA/ClimaCalibrate.jl

src/atmos_interface.jl
src/ekp_interface.jl

Since we already use `kill-on-invalid-dep` for sbatch scripts, this satisfies the minimal error handling requirement.
Closes #22

Add `SampleSuccGauss()` EKP failure handler, fill crashed sim output with NaNs

---

src/emulate_sample.jl
test/test_emulate_sample.jl

Don't return constrained posterior in `save_posterior`

---

.github/workflows/ci.yml
experiments/pipeline.jl
experiments/surface_fluxes_perfect_model/Manifest.toml
experiments/surface_fluxes_perfect_model/model_interface.jl
experiments/surface_fluxes_perfect_model/prior.toml
src/ekp_interface.jl
test/runtests.jl
test/test_emulate_sample.jl
test/test_model_interface.jl
test/test_sf.jl

This PR adds an end-to-end test for the surfacefluxes perfect model experiment.
Content
- Add `calibrate`, which runs the full calibration pipeline in a single function. This requires that the proper environment and model interface has already been loaded
- Use `calibrate` in the pipeline.jl (tested locally)
- Add end-to-end test using `calibrate` in `test/test_sf.jl`. I am a bit concerned that the parameter values are incorrect, since they do not match the default parameter values. 
- Add a unit test to ensure `calibrate` errors properly without the correct model interface
- resolve the surfacefluxes experiment Manifest
- Update the GHA

Add surfacefluxes test to CI

---

.github/workflows/ci.yml
docs/src/api.md
docs/src/atmos_setup_guide.md
docs/src/emulate_sample.md
docs/src/precompilation.md
experiments/surface_fluxes_perfect_model/generate_data.jl
experiments/surface_fluxes_perfect_model/model_interface.jl
experiments/surface_fluxes_perfect_model/observation_map.jl
experiments/surface_fluxes_perfect_model/postprocessing.jl
src/backends.jl
src/ekp_interface.jl
src/model_interface.jl
src/slurm.jl
test/ekp_interface.jl
test/model_interface.jl
test/pure_julia_e2e.jl
test/slurm_unit_tests.jl

Simplify model interface and remove experiment ID

---

src/backends.jl
src/ekp_interface.jl
test/ekp_interface.jl

Add kwargs for EKP to `initialize`

---

.buildkite/pipeline.yml
docs/src/quickstart.md
src/backends.jl
src/slurm.jl
test/caltech_hpc_e2e.jl
test/slurm_unit_tests.jl

Add ClimaGPU Backend

---

src/slurm.jl
test/slurm_unit_tests.jl

Improve slurm controller

---

experiments/surface_fluxes_perfect_model/Manifest.toml
src/ekp_interface.jl
src/slurm.jl

Add a new `initialize` method to work with EKP `ObservationSeries`. This may not be merged, since it is just a quickfix for now

initialize func without noise input

---

.github/workflows/ci.yml
src/backends.jl
src/ekp_interface.jl

This PR changes `update_ensemble` to return the termination flag passed by EKP, which is in turn checked with `!isnothing(terminate)`. 
Closes #104

Enable early termination

---

Project.toml
src/backends.jl
src/ekp_interface.jl
test/Project.toml
test/ekp_interface.jl
test/pure_julia_e2e.jl
test/runtests.jl

- Add `calibrate(; ekp = ekp::EnsembleKalmanProcess)` functionality
- Improve keyword tests

Fix JuliaBackend `calibrate` constructor

---

src/slurm.jl
test/slurm_unit_tests.jl

This PR removes dependency on `sacct` and `slurmdbd`, closing #115. 
On important consequence: We no longer track job failures for the `SlurmBackend`. Any job not found in the queue is just marked as completed.
----

Use `squeue` to find a Slurm job's status

---

.github/workflows/ci.yml
docs/src/api.md
docs/src/atmos_setup_guide.md
experiments/surface_fluxes_perfect_model/Manifest.toml
experiments/surface_fluxes_perfect_model/experiment_config.yml
experiments/surface_fluxes_perfect_model/generate_data.jl
experiments/surface_fluxes_perfect_model/model_config.yml
experiments/surface_fluxes_perfect_model/model_interface.jl
experiments/surface_fluxes_perfect_model/postprocessing.jl
src/ClimaCalibrate.jl
src/backends.jl
src/ekp_interface.jl
src/model_interface.jl
src/pbs.jl
src/slurm.jl
src/slurm_workers.jl
src/workers.jl
test/hpc_backend_e2e.jl
test/model_interface.jl
test/pbs_unit_tests.jl
test/pure_julia_e2e.jl
test/slurm_unit_tests.jl
test/slurm_workers.jl

This PR adds basic support for calibrations parallelized with Distributed.jl's remote workers. This mostly copies SlurmManager functionality from ClusterManagers.jl with some simplifications. ClusterManagers has been unmaintained for a while now and this PR allows us to control and test the features we need for parallelizing calibration.
Core changes:
- `set_up_forward_model` and `run_forward_model` are now combined into one function, `forward_model`
- `SlurmManager`: subtype of ClusterManager
- `worker_calibrate` and `run_iteration`: actual calibration functions
- cleaned up methods for `initialize`, `calibrate`, added `ekp_constructor`

Add support for Distributed.jl workers

---

docs/make.jl
docs/src/api.md
docs/src/backends.md
docs/src/index.md
docs/src/interface.md
docs/src/quickstart.md
experiments/surface_fluxes_perfect_model/postprocessing.jl
src/backends.jl
src/ekp_interface.jl
src/workers.jl
test/hpc_backend.jl
test/julia_backend.jl
test/sf_calibration_utils.jl

Improve SlurmManager readability, add env inheritance

---

docs/Project.toml
docs/literate_example.jl
docs/make.jl

Add example calibration using workers to docs

---

Project.toml
src/workers.jl
test/pbs_manager_unit_tests.jl
test/slurm_manager_unit_tests.jl

This PR unifies the polling for slurm and PBS systems into one function which now has a longer timeout. On both systems, julia workers will create their own file loggers from now on.
The main purpose of this PR is to return an error if the job submission fails. Before, the error would log but Julia would continue waiting for the worker.

Return error on failed scheduled job submission

---

README.md
docs/src/api.md
docs/src/quickstart.md
experiments/surface_fluxes_perfect_model/Manifest.toml
experiments/surface_fluxes_perfect_model/Project.toml
experiments/surface_fluxes_perfect_model/observation_map.jl
src/backends.jl
src/ekp_interface.jl
test/Project.toml
test/ekp_interface.jl
test/hpc_backend.jl
test/julia_backend.jl

This PR simplifies the source code by removing the unused ExperimentConfig struct. We can always add a new struct if we decide we need an extra layer to store experiment information.
- Remove `ExperimentConfig`
- Simplify backend dispatch to filter kwargs instead of having a method per backend. This will keep the code more maintainable as we add new backends.
- Updated surface fluxes test compat and Manifest
----

Remove unused ExperimentConfig struct

---

docs/src/api.md
src/backends.jl
src/workers.jl
test/hpc_backend.jl
test/pbs_manager_unit_tests.jl
test/slurm_manager_unit_tests.jl

This PR adds a function `add_workers` that provides user-friendly defaults. Closes #170 
- Added `GCPBackend`
- Added `add_workers(nworkers; device = :gpu, cluster_type = :auto, kwargs...)`, which automatically detects the manager and supplies default kwargs for the compute environment.
----

Add default function to add workers

---

.github/workflows/julia_formatter.yml
docs/make.jl
docs/src/api.md
docs/src/observations.md
src/ekp_interface.jl
src/workers.jl
test/ekp_interface.jl

This PR adds functions to help construct minibatches and observation series from vectors of data. Closes #169 
- Add documentation
- `minibatcher_over_samples(n_samples, batch_size)` takes in a number of samples and a batch size and returns a `FixedMinibatcher`. `minibatcher_over_samples(samples, batch_size)` does the same but takes in the actual samples.
- `observation_series_from_samples(samples, batch_size, names = nothing)` creates an `ObservationSeries` from the samples with the proper minibatcher.
----

Add minibatch helper functions

---

ext/ClimaAnalysisExt.jl
test/observation_recipe.jl

closes #203 - There is a bug when using latitude weights with `NaN` in the data. This bug is resolved by inserting `NaN` in the latitude weights whether there is `NaN` in the data. The `NaN`s are removed when flattening the data.

Fix latitude weights with NaN in data

---

ext/ClimaAnalysisExt.jl
src/observation_recipe.jl
test/observation_recipe.jl

This commit adds `ObservationRecipe.short_names` which get the short names of the variables in the observation.
TODO list

Add ObservationRecipe.short_names

---

docs/src/ensemble_builder.md
ext/ensemble_builder.jl
test/ensemble_builder.jl

closes #236 - This removes the functionality of passing multiple `OutputVar`s to `fill_g_ens_col!` and makes `fill_g_ens_col!` return a boolean indicating success or failure.

Improvements to fill_g_ens_col!
